var __SyzerUsage=class{constructor(runner){this.runner=runner||null;this.scanPromise=null;this.file=null;this.state={schemaVersion:1,scanState:{enabled:!1,lastScanStartedAt:null,lastScanCompletedAt:null,lastScanError:null},daily:[],sessions:[]};try{this.file=require(`node:path`).join(I.app.getPath(`userData`),`orca-syzer-usage.json`);let e=require(`node:fs`);if(e.existsSync(this.file)){let t=JSON.parse(e.readFileSync(this.file,`utf-8`));t&&t.schemaVersion===1&&(this.state={schemaVersion:1,scanState:{...this.state.scanState,...t.scanState},daily:Array.isArray(t.daily)?t.daily:[],sessions:Array.isArray(t.sessions)?t.sessions:[]})}}catch(e){console.error(`[syzer-usage] load failed`,e)}}
save(){try{this.file&&require(`node:fs`).writeFileSync(this.file,JSON.stringify(this.state))}catch(e){console.error(`[syzer-usage] save failed`,e)}}
getScanState(){return{...this.state.scanState,isScanning:this.scanPromise!==null,hasAnySyzerData:this.state.daily.length>0||this.state.sessions.length>0}}
async flush(){this.save()}
async setEnabled(e){return this.state.scanState.enabled=!!e,this.save(),this.getScanState()}
async refresh(e=!1){let t=this.state.scanState;return t.enabled?((e||!t.lastScanCompletedAt||Date.now()-t.lastScanCompletedAt>=3e5)&&await this.runScan(),this.getScanState()):this.getScanState()}
async runScan(){if(this.scanPromise){await this.scanPromise;return}let e=this.state.scanState;e.lastScanStartedAt=Date.now(),e.lastScanError=null,this.scanPromise=(async()=>{try{let t=await(this.runner||__syzerRun)(),n=__syzerNormalize(t);this.state.daily=n.daily,this.state.sessions=n.sessions,e.lastScanCompletedAt=Date.now(),e.lastScanError=null}catch(t){e.lastScanError=t instanceof Error?t.message:String(t)}finally{this.save(),this.scanPromise=null}})(),await this.scanPromise}
start(e){if(e===`all`||!e)return null;let t=e===`7d`?7:e===`30d`?30:e===`90d`?90:0;if(!t)return null;let n=new Date;return n.setHours(0,0,0,0),n.setDate(n.getDate()-(t-1)),__syzerDay(n)}
fd(e){let t=this.start(e);return t?this.state.daily.filter(e=>e.day>=t):this.state.daily}
fs(e){let t=this.start(e);return t?this.state.sessions.filter(e=>{let n=__syzerDay(new Date(e.lastTimestamp));return n&&n>=t}):this.state.sessions}
buildSummary(e,t){let n=this.fd(t),r=this.fs(t),i={inputTokens:0,cachedInputTokens:0,outputTokens:0,reasoningOutputTokens:0,totalTokens:0},a=0,o=null,s=new Map,c=new Map;for(let e of n){for(let t in i)i[t]+=e[t];a+=e.eventCount,e.estimatedCostUsd!=null&&(o=(o??0)+e.estimatedCostUsd),s.set(e.model??`Unknown model`,(s.get(e.model??`Unknown model`)??0)+e.totalTokens),c.set(e.projectLabel,(c.get(e.projectLabel)??0)+e.totalTokens)}let l=e=>{let t=null,n=-1/0;for(let[r,i]of e)i>n&&(t=r,n=i);return t};return{scope:e,range:t,sessions:r.length,events:a,...i,estimatedCostUsd:o,topModel:l(s),topProject:l(c),hasAnySyzerData:r.length>0||n.length>0}}
buildDaily(e){let t=new Map;for(let n of this.fd(e)){let e=t.get(n.day)??{day:n.day,inputTokens:0,cachedInputTokens:0,outputTokens:0,reasoningOutputTokens:0,totalTokens:0};e.inputTokens+=n.inputTokens,e.cachedInputTokens+=n.cachedInputTokens,e.outputTokens+=n.outputTokens,e.reasoningOutputTokens+=n.reasoningOutputTokens,e.totalTokens+=n.totalTokens,t.set(n.day,e)}return[...t.values()].sort((e,t)=>e.day.localeCompare(t.day))}
buildBreakdown(e,t,n){let r=this.fd(t),i=this.fs(t),a=new Map,o=n===`model`;for(let e of r){let t=o?e.model??`unknown`:e.projectKey,n=a.get(t)??{key:t,label:o?e.model??`Unknown model`:e.projectLabel,sessions:0,events:0,inputTokens:0,cachedInputTokens:0,outputTokens:0,reasoningOutputTokens:0,totalTokens:0,estimatedCostUsd:null};n.events+=e.eventCount,n.inputTokens+=e.inputTokens,n.cachedInputTokens+=e.cachedInputTokens,n.outputTokens+=e.outputTokens,n.reasoningOutputTokens+=e.reasoningOutputTokens,n.totalTokens+=e.totalTokens,e.estimatedCostUsd!=null&&(n.estimatedCostUsd=(n.estimatedCostUsd??0)+e.estimatedCostUsd),a.set(t,n)}for(let e of i)for(let t of new Set(o?e.models:e.projectKeys)){let e=a.get(t);e&&e.sessions++}return[...a.values()].sort((e,t)=>t.totalTokens-e.totalTokens)}
buildRecent(e,t=10){return this.fs(e).slice().sort((e,t)=>String(t.lastTimestamp).localeCompare(String(e.lastTimestamp))).slice(0,t).map(e=>({sessionId:e.sessionId,lastActiveAt:e.lastTimestamp,durationMinutes:Math.max(0,Math.round((new Date(e.lastTimestamp).getTime()-new Date(e.firstTimestamp).getTime())/6e4)),projectLabel:e.primaryProjectLabel,model:e.primaryModel,events:e.eventCount,inputTokens:e.totalInputTokens,cachedInputTokens:e.totalCachedInputTokens,outputTokens:e.totalOutputTokens,reasoningOutputTokens:e.totalReasoningOutputTokens,totalTokens:e.totalTokens}))}
getSnapshot(e,t,n=10){return{scanState:this.getScanState(),summary:this.buildSummary(e,t),daily:this.buildDaily(t),modelBreakdown:this.buildBreakdown(e,t,`model`),projectBreakdown:this.buildBreakdown(e,t,`project`),recentSessions:this.buildRecent(t,n)}}
async getSummary(e,t){return await this.refresh(!1),this.buildSummary(e,t)}
async getDaily(e,t){return await this.refresh(!1),this.buildDaily(t)}
async getBreakdown(e,t,n){return await this.refresh(!1),this.buildBreakdown(e,t,n)}
async getRecentSessions(e,t,n=10){return await this.refresh(!1),this.buildRecent(t,n)}};
function __syzerDay(e){return Number.isNaN(e.getTime())?null:`${e.getFullYear()}-${String(e.getMonth()+1).padStart(2,`0`)}-${String(e.getDate()).padStart(2,`0`)}`}
function __syzerN(e){return typeof e==`number`&&Number.isFinite(e)&&e>=0?Math.round(e):0}
function __syzerNormalize(e){if(!e||typeof e!=`object`||e.schemaVersion!==1)throw Error(`syzer stats: unsupported schemaVersion`);let t=e=>e==null||typeof e!=`number`||!Number.isFinite(e)?null:e,n=e=>({inputTokens:__syzerN(e.inputTokens),cachedInputTokens:Math.min(__syzerN(e.cachedInputTokens),__syzerN(e.inputTokens)),outputTokens:__syzerN(e.outputTokens),reasoningOutputTokens:__syzerN(e.reasoningOutputTokens)}),r=(Array.isArray(e.daily)?e.daily:[]).filter(e=>e&&/^\d{4}-\d{2}-\d{2}$/.test(e.day)).map(e=>{let r=n(e);return{day:e.day,model:typeof e.model==`string`&&e.model?e.model:null,projectKey:String(e.projectKey??`unscoped`),projectLabel:String(e.projectLabel??`Unknown location`),...r,totalTokens:r.inputTokens+r.outputTokens,eventCount:__syzerN(e.eventCount),estimatedCostUsd:t(e.estimatedCostUsd)}}),i=(Array.isArray(e.sessions)?e.sessions:[]).filter(e=>e&&e.sessionId&&!Number.isNaN(new Date(e.lastTimestamp).getTime())).map(e=>{let r=__syzerN(e.totalInputTokens),i=__syzerN(e.totalOutputTokens);return{sessionId:String(e.sessionId),firstTimestamp:Number.isNaN(new Date(e.firstTimestamp).getTime())?e.lastTimestamp:e.firstTimestamp,lastTimestamp:e.lastTimestamp,primaryModel:e.primaryModel??null,primaryProjectLabel:String(e.primaryProjectLabel??`Unknown location`),models:Array.isArray(e.models)?e.models.map(String):[],projectKeys:Array.isArray(e.projectKeys)?e.projectKeys.map(String):[],eventCount:__syzerN(e.eventCount),totalInputTokens:r,totalCachedInputTokens:Math.min(__syzerN(e.totalCachedInputTokens),r),totalOutputTokens:i,totalReasoningOutputTokens:__syzerN(e.totalReasoningOutputTokens),totalTokens:r+i}});return{daily:r,sessions:i}}
function __syzerRun(){return new Promise((e,t)=>{let n=process.env.SYZER_BIN||`syzer`;require(`node:child_process`).execFile(n,[`stats`,`--json`,`--usage-analytics`],{shell:process.platform===`win32`,windowsHide:!0,timeout:12e4,maxBuffer:268435456,env:process.env},(n,r,i)=>{if(n)return t(Error(`syzer stats failed: ${String(i||n.message).trim().slice(0,300)}`));let a=r.indexOf(`{`),o=r.lastIndexOf(`}`);try{e(JSON.parse(r.slice(a,o+1)))}catch{t(Error(`syzer stats: invalid JSON output`))}})})}
var __syzerSvc=null;function __getSyzerUsage(){return __syzerSvc??=new __SyzerUsage}
